### PR TITLE
Cache busting via language versions

### PR DESCRIPTION
**Pull request by Silviu-Marian**
This introduces the feature we talked about (#2): 
- changelog typo + update
- readme update
- the feature
- some eslint corrections (they happen automatically when I save, so please let me know and I'll put them)
- rebuilt the whole thing

Whole thing is tested. It's very simple
Essentially you'd pass in an object in a config, that looks like this:
``` 
{
  // ...
  versions: {
    'en': 'mtq4nzk3',
    'fr': '21ja9ka2',
    'de': 'xio32skd',
    'it': 'ak8xakld',
  }
}
```

Now when any of those hashes change, or if expiry time is hit, the cache will be invalidated
You can omit this altogether and rely on expiration entirely

Thank you :)

### CODE REVIEW

**Comment by jamuhl** [comment]
thanks for contributing this. really appreciate every help on making i18next better.

published in: i18next-localstorage-cache@1.1.0

**Comment by trajano** [comment]
Is there a sample of how to use this?  Especially with WebPack?  I am thinking that the versions is actually keyed on localStorage cache so if it does not match there then it will pull it's not based on any file name  mangling that WebPack would normally do.

**Comment by jamuhl** [comment]
nothing to do with webpack. If the version changed from last deploy/build whatever the resources are pulled again as not taken from cache.

**Comment by trajano** [comment]
What I am trying to see is if we can get the "versions" populated by WebPack somehow.  Still haven't found out how to do that yet.

**Comment by jamuhl** [comment]
still not sure what this has todo with webpack....eg. require package.json and use the version from there...idk

**Comment by trajano** [comment]
I guess that would work too.  WebPack provides the capability of generating
a hash for every build so I am hoping to utilize that rather than changing
versions internally or disabling cache.

**Comment by jamuhl** [comment]
ah...ok...might be this helps? http://stackoverflow.com/questions/24663175/how-can-i-inject-a-build-number-with-webpack

**Comment by Silviu-Marian** [comment]
Getting the same hash that webpack generates be bled into the code is a bit tricky. You can still achieve that through stats plugin, by reading it from the json, or a custom variable stored globally with htmlwebpackplugin. 

There's also provideplugin, you can do Date.now() and have it replace a variable in your code, which you then append to all languages you support. 

What's your setup so far? Can you share some code with us?

**Comment by trajano** [comment]
My setup isn't too far in yet, I just plopped in i18next recently to see what can be done.  The concept was to provide a "framework" that people can extend.  I'm looking into http://i18next.com/docs/api/#add-resource-bundle as we speak where the extenders can put in their own translations outside the framework for their own components.

My i18n.js is basically a copy from the sample https://github.com/trajano/reactjs-admin/blob/master/src/framework/i18n.js


https://trajano.github.io/reactjs-admin/
https://github.com/trajano/reactjs-admin

**Comment by Silviu-Marian** [comment]
I said ProvidePlugin instead of DefinePlugin. 
Basically just follow the SO answer @jamuhl provided and you should be ok. :)

**Pull request merged**
